branch-defaults:
  default:
    environment: environment-name
environment-defaults:
  datahub-live:
    branch: null
    repository: null
global:
  application_name: datahub
  default_ec2_keyname: null
  default_platform: docker-20.10.13-ce
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
