version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4584:4563-4584'
      - '8080:8080'
    environment:
      - SERVICES=s3,sqs,opensearch,dynamodb
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - './.localstack:/var/lib/localstack'
